
import ThemeProvider from './components/ThemeProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Baskket',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <ThemeProvider>
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
